### ISSUE TITLE
DuplicateFileException: Duplicate files copied in APK about.mappings

### ISSUE THREAD

**Issue by karthick229** [siteadmin/code-validator-api#44]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK about.mappings
  	File1: /home/ansari/Music/Health-Hive/app/libs/org.eclipse.emf.ecore-2.11.2.v20160208-0816.jar
  	File2: /home/ansari/Music/Health-Hive/app/libs/org.eclipse.emf.common-2.11.1.v20160208-0816.jar

**adding files...............**
compile files('libs/org.eclipse.emf.common-2.11.1.v20160208-0816.jar')
compile files('libs/org.eclipse.emf.ecore.xmi-2.11.1.v20160208-0816.jar')
compile files('libs/org.eclipse.emf.ecore-2.11.2.v20160208-0816.jar')

**mydependencies...**

packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'

    }

**Comment by drbgfc** [comment]
Hard to tell what's going on out of context, but, those (eclipse.emf) jars are MDHT dependencies. They should not be dependencies of this project. If you are using any of the SITE C-CDA validator projects (referenceccdavalidator, etc.) they leverage MDHT and will include those dependencies. So, maybe you are adding them manually, in addtion to using one of the C-CDA projects, creating the duplicate error?
