### ISSUE TITLE
VSAC valuesets are not loading.

### ISSUE THREAD

**Issue by tircnf** [siteadmin/code-validator-api#47]
VSAC valuesets are not loading anymore.

if you download a VSAC file, the OID has been moved from row 3 to row 4.

VsacLoader.java lines 53 to 65 are accessing the incorrect row index.

Here is a snippet of the top of a VSAC download file.  You can see that "Code System" was inserted before OID.

![image](https://user-images.githubusercontent.com/1508602/28904086-28e2a9ee-77ce-11e7-8207-b4cc547dc800.png)

**Comment by Plow74** [comment]
Ugh. We are looking into this and will keep the community posted. Thanks!

**Comment by Plow74** [comment]
This should be fixed with the newest release. Thanks!
