### ISSUE TITLE
PostalCode.xlsx using wrong Value Set Name and OID

### ISSUE THREAD

**Issue by acostanxt** [siteadmin/code-validator-api#49]
The header for PostalCode.xlsx has:
Value Set Name: Medication Clinical General Drug
OID: 2.16.840.1.113883.3.88.12.80.17

Correct values should probably:
Value Set Name: Postal Code
OID: 2.16.840.1.113883.3.88.12.80.2

**Comment by drbgfc** [comment]
This is no longer an issue. Thank you. Sorry for the (massive :-) ) delay.
