### ISSUE TITLE
how to run the project ?

### ISSUE THREAD

**Issue by usmanq8** [siteadmin/code-validator-api#51]
which file is needed to run the project i am able to compile the project and set env. variables. and placed valueset files

**Comment by drbgfc** [comment]
I believe these questions have been answered here? 
https://github.com/siteadmin/reference-ccda-validator/issues/26
https://github.com/siteadmin/reference-ccda-validator/issues/27

If you have more specific questions please let me know. Please be as specific as possible, thanks.

The main file to run the project is the war latest file here https://github.com/siteadmin/reference-ccda-validator/releases
